version: '3.8'
services:
app_blue:
image: "${BLUE_IMAGE}"
environment:
- RELEASE_ID=${RELEASE_ID_BLUE}
- APP_POOL=blue
- PORT=${PORT:-3000}
ports:
- "8081:3000" # grader will call this
healthcheck:
test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"]
interval: 2s
timeout: 2s
retries: 2


app_green:
image: "${GREEN_IMAGE}"
environment:
- RELEASE_ID=${RELEASE_ID_GREEN}
- APP_POOL=green
- PORT=${PORT:-3000}
ports:
- "8082:3000"
healthcheck:
test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"]
interval: 2s
timeout: 2s
retries: 2


nginx:
image: nginx:stable
depends_on:
- app_blue
- app_green
ports:
- "8080:80"
volumes:
- ./nginx-entrypoint.sh:/docker-entrypoint.d/nginx-entrypoint.sh:ro
- ./nginx.conf.template:/etc/nginx/templates/nginx.conf.template:ro
environment:
- ACTIVE_POOL=${ACTIVE_POOL}
- BLUE_HOST=app_blue:3000
- GREEN_HOST=app_green:3000
healthcheck:
test: ["CMD", "curl", "-f", "http://localhost/version" ]
interval: 3s
timeout: 3s
retries: 3


networks:
default:
name: bg-net
